image: node:14.5

pages:
  script:
    - npm install
    - mkdir .public
    - cp -r * .public
    - mv .public public
    - cp $CONFIG_PROD public/config.json
  artifacts:
    paths:
      - public
  only:
    - master

tests:
  script:
    - npm install
    - npm run test

